#!/usr/bin/python3 -u

import argparse
import os
import signal

import heal


def is_directory(value):
    if not os.path.isdir(value):
        raise argparse.ArgumentTypeError("not a directory")
    return value


def is_writable(value):
    try:
        open(value, "w").close()
    except IOError:
        raise argparse.ArgumentTypeError("not a writable file")
    return value


argparser = argparse.ArgumentParser(description="Minimalist self-healing.")
argparser.add_argument("-c", "--configuration-directory", default="/etc/heal.conf.d", type=is_directory, help="path to the yaml or json configuration directory (default: /etc/heal.conf.d)")
args = argparser.parse_args()

# handles signals properly
for sig in [signal.SIGINT, signal.SIGTERM]:
    signal.signal(sig, heal.shutdown)

heal.MasterThread(args.configuration_directory).start()
